spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/emailsender
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.office365.com
    port: 587
    username: maldf@outlook.pt
    password: #whpHB?FytrMF?5[
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect